import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "../styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";
import Provider from "@/components/Provider";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className=" font-mono ">
        <ClerkProvider>
          <TRPCReactProvider>
            <Provider>
              <ThemeProvider>
                <NextTopLoader /> {children}
              </ThemeProvider>
            </Provider>
          </TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
